language: c
os: linux
dist: focal
script: make tests
addons:
  apt:
    packages:
    - libpulse-dev
    - libavcodec-dev
    - libavformat-dev
    - libswresample-dev
    - pulseaudio
jobs:
  include:
    - compiler: gcc
      arch: amd64
      env:
        - COMPILER=gcc
        - COVERAGE=${COVERALLS_REPO_TOKEN:+Y}
    - compiler: clang
      arch: amd64
      env:
        - COMPILER=clang
    - compiler: gcc
      arch: arm64
      env:
        - COMPILER=gcc
env:
  global:
    - CFLAGS="$CFLAGS${CFLAGS:+ }-Werror"
    - CXXFLAGS="$CXXFLAGS${CXXFLAGS:+ }-Werror"
before_install:
  - export CXX="$COMPILER"
  - export CC="$COMPILER"
  - ${CXX} --version
  - test "$COVERAGE" = "Y" && pip install --user cpp-coveralls || echo "Coveralls reporting skipped"
before_script:
  - pulseaudio --version
  - dbus-launch pulseaudio --start || pulseaudio --start
after_success:
  - test "$COVERAGE" = "Y" && coveralls --exclude /usr/include/ || echo "Coveralls reporting skipped"
