language: c
os: linux
dist: bionic
script: make tests
addons:
  apt:
    packages:
    - libpulse-dev
    - libavcodec-dev
    - libavformat-dev
    - libswresample-dev
    - pulseaudio
jobs:
  include:
    - compiler: gcc
      env:
        - COMPILER=gcc
    - compiler: clang
      env:
        - COMPILER=clang
env:
  global:
    - CFLAGS="$CFLAGS${CFLAGS:+ }-Werror"
    - CXXFLAGS="$CXXFLAGS${CXXFLAGS:+ }-Werror"
before_install:
  - export CXX="$COMPILER"
  - export CC="$COMPILER"
  - ${CXX} --version
before_script:
  - dbus-launch pulseaudio --start
