language: c
dist: trusty
sudo: required
script: make
matrix:
  include:
    - compiler: gcc
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
        - sudo apt-get update -qq
        - sudo apt-get install -qq gcc-6 libpulse-dev libavcodec-dev libavformat-dev libswresample-dev
      env:
        - COMPILER=gcc-6
    - compiler: clang
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
        - sudo apt-get update -qq
        - sudo apt-get install -qq clang-3.9 llvm-3.9-dev libpulse-dev libavcodec-dev libavformat-dev libswresample-dev
      env:
        - COMPILER=clang-3.9
env:
  global:
    - CFLAGS="$CFLAGS${CFLAGS:+ }-Werror"
    - CXXFLAGS="$CXXFLAGS${CXXFLAGS:+ }-Werror"
before_install:
  - export CXX="$COMPILER"
  - export CC="$COMPILER"
  - ${CXX} --version
